# fly.toml app configuration file generated for soulmaking-companion on 2026-02-06T18:33:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'soulmaking-companion'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[env]
  PB_ORIGINS = 'https://clemensjakob.github.io/soulmaking-companion/'
  PORT = '8080'

[[mounts]]
  source = 'pb_data'
  destination = '/pb/pb_data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
